In [4]:
import numpy as np

In [7]:
a = np.array([1,2,3,4])

In [8]:
a

array([1, 2, 3, 4])

In [9]:
print(type(a))

<class 'numpy.ndarray'>


print(a.shape)

In [7]:
print(a.shape)

(3,)


In [8]:
print([0],[1],[2],[3])

[0] [1] [2] [3]


In [9]:
b = np.array([[1,2],[3,4]])

In [10]:
print(b)

[[1 2]
 [3 4]]


In [11]:
print(b.shape)

(2, 2)


In [12]:
print(b[0,0],b[0,1],b[1,1])

1 2 4


In [14]:
c = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [15]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
print(c.shape)

(3, 3)


In [18]:
d = np.zeros((2,4))

In [19]:
d

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
e=np.full((3,3),5)

In [23]:
e

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [28]:
f = np.random.random((3,3))

In [29]:
f

array([[0.74587167, 0.74339443, 0.68817522],
       [0.37065897, 0.49649753, 0.34299919],
       [0.08547239, 0.64951144, 0.34023056]])

In [32]:
h= np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [33]:
h

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [34]:
i = h[:2, 1:3]

In [35]:
i

array([[2, 3],
       [6, 7]])

In [36]:
print(h[0,1])

2


In [37]:
i[0,0]=4585

In [38]:
i

array([[4585,    3],
       [   6,    7]])

In [39]:
j =np.array([1,2])

In [41]:
print(j.dtype)

int32


In [64]:
k=np.array([1.0,2.0])

In [65]:
print(k.dtype)

float64


In [68]:
x=np.array([[1,2],[3,4]], dtype=np.float64)
y=np.array([[5,6],[7,8]], dtype=np.float64)

In [69]:
a=x+y

In [71]:
a

array([[ 6.,  8.],
       [10., 12.]])

In [8]:
print("Mohammad Aadil",end=' ')
print("Shaikh")


Mohammad Aadil Shaikh


In [24]:
import numpy as np

In [25]:
a=np.array([1,2,3,4,5])

In [28]:
print(a)

[1 2 3 4 5]


In [29]:
print(type(a))

<class 'numpy.ndarray'>


In [37]:
b = np.array([[12,14],[15,16]])

In [38]:
print(b)

[[12 14]
 [15 16]]


In [39]:
print(type(b))

<class 'numpy.ndarray'>


In [40]:
print(b.shape)

(2, 2)


In [41]:
c = np.array([[2,4,6],[8,10,12],[14,16,18]])

In [42]:
c

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [43]:
print(type(c))

<class 'numpy.ndarray'>


In [44]:
print(c.shape)

(3, 3)


In [56]:
d=np.full((3,4),7)

In [54]:
d

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [61]:
e = np.random.random((4,5))

In [62]:
e

array([[0.6587045 , 0.08924557, 0.49388584, 0.18373004, 0.49649907],
       [0.7190293 , 0.60075825, 0.40593142, 0.62658257, 0.39528741],
       [0.79748896, 0.35921649, 0.13496924, 0.97988865, 0.37915795],
       [0.11979886, 0.46231667, 0.29805489, 0.27658462, 0.88604192]])